package Reportview;
// Generated May 12, 2020 3:27:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private int bookid;
     private String title;
     private String publishing;
     private Date dateofpub;
     private String author;
     private Integer pages;
     private String bookcate;

    public Book() {
    }

	
    public Book(int bookid) {
        this.bookid = bookid;
    }
    public Book(int bookid, String title, String publishing, Date dateofpub, String author, Integer pages, String bookcate) {
       this.bookid = bookid;
       this.title = title;
       this.publishing = publishing;
       this.dateofpub = dateofpub;
       this.author = author;
       this.pages = pages;
       this.bookcate = bookcate;
    }
   
    public int getBookid() {
        return this.bookid;
    }
    
    public void setBookid(int bookid) {
        this.bookid = bookid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishing() {
        return this.publishing;
    }
    
    public void setPublishing(String publishing) {
        this.publishing = publishing;
    }
    public Date getDateofpub() {
        return this.dateofpub;
    }
    
    public void setDateofpub(Date dateofpub) {
        this.dateofpub = dateofpub;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }
    public String getBookcate() {
        return this.bookcate;
    }
    
    public void setBookcate(String bookcate) {
        this.bookcate = bookcate;
    }




}


