package Reportview;
// Generated May 12, 2020 3:27:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private String client;
     private Date date;
     private String book;
     private String status;

    public Checkout() {
    }

	
    public Checkout(String client) {
        this.client = client;
    }
    public Checkout(String client, Date date, String book, String status) {
       this.client = client;
       this.date = date;
       this.book = book;
       this.status = status;
    }
   
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getBook() {
        return this.book;
    }
    
    public void setBook(String book) {
        this.book = book;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


