package Reportview;
// Generated May 12, 2020 3:27:44 PM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String fname;
     private String lname;
     private String phone;
     private String email;
     private String clientcat;
     private String image;

    public Client() {
    }

	
    public Client(int id) {
        this.id = id;
    }
    public Client(int id, String fname, String lname, String phone, String email, String clientcat, String image) {
       this.id = id;
       this.fname = fname;
       this.lname = lname;
       this.phone = phone;
       this.email = email;
       this.clientcat = clientcat;
       this.image = image;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClientcat() {
        return this.clientcat;
    }
    
    public void setClientcat(String clientcat) {
        this.clientcat = clientcat;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


