/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseassign;

/**
 *
 * @author pacifique
 */
import Connectivity.Checkincon;
import Connectivity.ConnectHibernateUtil;
import Connectivity.checkoutcon;
import Reportview.Checkin;
import Reportview.Checkout;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;
public class Operation extends javax.swing.JInternalFrame {

    /**
     * Creates new form Operation
     */
    DefaultTableModel model=null;
    DefaultTableModel model1=null;
    
    public Operation() {
        initComponents();
         model = (DefaultTableModel) checkintable.getModel();
         model1 = (DefaultTableModel) checkouttable.getModel();
        populateTable();
         populateTable1();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        cbclient = new javax.swing.JComboBox<>();
        cbbook = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkintable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnsave1 = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        cbclient1 = new javax.swing.JComboBox<>();
        cbbook1 = new javax.swing.JComboBox<>();
        txtstatus1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkouttable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("check out operation"));

        jLabel1.setText("Date Time");

        jLabel2.setText("Client");

        jLabel3.setText("Book");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");

        cbclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbclientMousePressed(evt);
            }
        });

        cbbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbookMousePressed(evt);
            }
        });

        jLabel7.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbclient, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbook, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtstatus, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnsave)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btndelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        checkintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Date Time", "Client", "Book", "Status"
            }
        ));
        jScrollPane1.setViewportView(checkintable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CheckIn", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("check out operation"));

        jLabel4.setText("Date Time");

        jLabel5.setText("Client");

        jLabel6.setText("Book");

        btnsave1.setText("Save");
        btnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave1ActionPerformed(evt);
            }
        });

        btnupdate1.setText("Update");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });

        btndelete1.setText("Delete");

        jLabel8.setText("Satus");

        cbclient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbclient1MousePressed(evt);
            }
        });

        cbbook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbook1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(cbclient1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbook1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtstatus1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnsave1)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndelete1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbclient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave1)
                    .addComponent(btnupdate1)
                    .addComponent(btndelete1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkouttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Date Time", "Client", "Book", "Status"
            }
        ));
        checkouttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkouttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(checkouttable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Check out", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        Checkin b=new Checkin();
       
                    b.setDate(new Date(date.getDate().getTime()));
                    b.setClient(cbclient.getSelectedItem().toString());
                    b.setBook(cbbook.getSelectedItem().toString());
                    
                    b.setStatus(txtstatus.getText());
                    
                    
                    
                    Checkincon d=new Checkincon();
                    d.saveCheckin(b);
                    populateTable();
                    JOptionPane.showMessageDialog(this,"data saved");
        
        
       

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dform=new SimpleDateFormat("MM/dd//yyy");
        Checkin b=new Checkin();
       
                    b.setDate(new Date(date.getDate().getTime()));
                    b.setClient(cbclient.getSelectedItem().toString());
                    b.setBook(cbbook.getSelectedItem().toString());
                    b.setStatus(txtstatus.getText());
                    
                    Checkincon d=new Checkincon();
                    d.updateCheckin(b);
                    populateTable();
                    JOptionPane.showMessageDialog(this,"data saved");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave1ActionPerformed
        // TODO add your handling code here:
       SimpleDateFormat dform=new SimpleDateFormat("MM/dd//yyy");
        Checkout b=new Checkout();
       
                    b.setDate(new Date(date1.getDate().getTime()));
                    b.setClient(cbclient1.getSelectedItem().toString());
                    b.setBook(cbbook1.getSelectedItem().toString());
                    b.setStatus(txtstatus1.getText());
                    
                    checkoutcon d=new checkoutcon();
                    d.saveCheckout(b);
                    populateTable();
                    JOptionPane.showMessageDialog(this,"data saved");
    }//GEN-LAST:event_btnsave1ActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        // TODO add your handling code here:
          SimpleDateFormat dform=new SimpleDateFormat("MM/dd//yyy");
        Checkout b=new Checkout();
       
                    b.setDate(new Date(date1.getDate().getTime()));
                    b.setClient(cbclient1.getSelectedItem().toString());
                    b.setBook(cbbook1.getSelectedItem().toString());
                    b.setStatus(txtstatus1.getText());
                    
                    checkoutcon d=new checkoutcon();
                    d.updateCheckout(b);
                    populateTable();
                    JOptionPane.showMessageDialog(this,"data saved");
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        int row = checkintable.getSelectedRow();
       
       // date.setText(model.getValueAt(row, 0).toString());
        cbclient.setSelectedItem(model.getValueAt(row, 1).toString());
        cbbook.setSelectedItem(model.getValueAt(row, 2).toString());
        txtstatus.setText(model.getValueAt(row, 4).toString());
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void checkouttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkouttableMouseClicked
        // TODO add your handling code here:
       int row = checkouttable.getSelectedRow();
       
       // date1.setText(model.getValueAt(row, 0).toString());
        cbclient1.setSelectedItem(model.getValueAt(row, 1).toString());
        cbbook1.setSelectedItem(model.getValueAt(row, 2).toString());
        txtstatus1.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_checkouttableMouseClicked

    private void cbclient1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbclient1MousePressed
        // TODO add your handling code here:
        cbclient1.removeAllItems();
                    Transaction tr=null;
                    Session sess=ConnectHibernateUtil.getSessionFactory().openSession();
                    tr=sess.beginTransaction();
                    SQLQuery query=sess.createSQLQuery("select fname from Client");
                    List ls=query.list();
                    for(Object boca:ls)
                    {
                    cbclient1.addItem((String)boca);
                    }
    }//GEN-LAST:event_cbclient1MousePressed

    private void cbbook1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbook1MousePressed
        // TODO add your handling code here:
        cbbook1.removeAllItems();
                    Transaction tr=null;
                    Session sess=ConnectHibernateUtil.getSessionFactory().openSession();
                    tr=sess.beginTransaction();
                    SQLQuery query=sess.createSQLQuery("select title from Book");
                    List ls=query.list();
                    for(Object boca:ls)
                    {
                    cbbook1.addItem((String)boca);
                    }
    }//GEN-LAST:event_cbbook1MousePressed

    private void cbclientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbclientMousePressed
        // TODO add your handling code here:
        cbclient.removeAllItems();
                    Transaction tr=null;
                    Session sess=ConnectHibernateUtil.getSessionFactory().openSession();
                    tr=sess.beginTransaction();
                    SQLQuery query=sess.createSQLQuery("select fname from Client");
                    List ls=query.list();
                    for(Object boca:ls)
                    {
                    cbclient.addItem((String)boca);
                    }
    }//GEN-LAST:event_cbclientMousePressed

    private void cbbookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbookMousePressed
        // TODO add your handling code here:
        cbbook.removeAllItems();
                    Transaction tr=null;
                    Session sess=ConnectHibernateUtil.getSessionFactory().openSession();
                    tr=sess.beginTransaction();
                    SQLQuery query=sess.createSQLQuery("select title from Book");
                    List ls=query.list();
                    for(Object boca:ls)
                    {
                    cbbook.addItem((String)boca);
                    }
    }//GEN-LAST:event_cbbookMousePressed
    private void populateTable() {
           Checkincon c=new Checkincon();
             List<Checkin>b=c.listAll();
    DefaultTableModel model=(DefaultTableModel)checkintable.getModel();
    model.setRowCount(0);
    for(Checkin rs:b){
       Object[] obj=new Object[]{rs.getDate(),rs.getClient(),rs.getBook(),rs.getStatus()};
       model.addRow(obj);
    }
           
          
    }
       private void populateTable1() {
            
           checkoutcon c=new checkoutcon();
             List<Checkout>b=c.listAll();
    DefaultTableModel model=(DefaultTableModel)checkouttable.getModel();
    model.setRowCount(0);
    for(Checkout rs:b){
       Object[] obj=new Object[]{rs.getDate(),rs.getClient(),rs.getBook(),rs.getStatus()};
       model.addRow(obj);
    }
         
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsave1;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JComboBox<String> cbbook;
    private javax.swing.JComboBox<String> cbbook1;
    private javax.swing.JComboBox<String> cbclient;
    private javax.swing.JComboBox<String> cbclient1;
    private javax.swing.JTable checkintable;
    private javax.swing.JTable checkouttable;
    private com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtstatus1;
    // End of variables declaration//GEN-END:variables
}
